name: L10n Update

on:
  push:
    branches:
      - master

jobs:
  trigger-update:
    name: L10n Update Trigger
    runs-on: ubuntu-latest

    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ICINGABOT_TOKEN }}
          repository: Icinga/L10n
          event-type: update
          client-payload: '{"origin": "${{ github.repository }}", "commit": "${{ github.sha }}"}'
